name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build and Test"
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity detailed
  deploy:
    name: "Deploy to Docker"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: pronoytw/bubbles
          tag: v1
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}